-- MySQL Script generated by MySQL Workbench
-- Sat Feb 20 11:45:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`teacher` ;

CREATE TABLE IF NOT EXISTS `school`.`teacher` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `second_surname` VARCHAR(100) NULL,
  `age` INT NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `identification` VARCHAR(45) NOT NULL,
  `image` VARCHAR(100) NULL,
  `status` INT NOT NULL DEFAULT 1,
  `date_reg` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `identification_UNIQUE` (`identification` ASC) )
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `school`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`grade` ;

CREATE TABLE IF NOT EXISTS `school`.`grade` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `teacher_id` BIGINT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `date_reg` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_course_teacher_idx` (`teacher_id` ASC) ,
  UNIQUE INDEX `teacher_id_UNIQUE` (`teacher_id` ASC) ,
  CONSTRAINT `fk_course_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `school`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`student` ;

CREATE TABLE IF NOT EXISTS `school`.`student` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `second_surname` VARCHAR(100) NULL,
  `age` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `image` VARCHAR(100) NULL,
  `status` INT NOT NULL DEFAULT 1,
  `date_reg` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `grade_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_course1_idx` (`grade_id` ASC) ,
  CONSTRAINT `fk_student_course1`
    FOREIGN KEY (`grade_id`)
    REFERENCES `school`.`grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `school`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`course` ;

CREATE TABLE IF NOT EXISTS `school`.`course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `school`.`shelude`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`shelude` ;

CREATE TABLE IF NOT EXISTS `school`.`shelude` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `grade_id` BIGINT NOT NULL,
  `course_id` BIGINT NOT NULL,
  `teacher_id` BIGINT NOT NULL,
  `date_start` DATETIME NOT NULL,
  `date_end` DATETIME NOT NULL,
  `estatus` INT NOT NULL DEFAULT 1,
  INDEX `fk_grade_has_course_course1_idx` (`course_id` ASC) ,
  INDEX `fk_grade_has_course_grade1_idx` (`grade_id` ASC) ,
  INDEX `fk_grade_has_course_teacher1_idx` (`teacher_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_grade_has_course_grade1`
    FOREIGN KEY (`grade_id`)
    REFERENCES `school`.`grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grade_has_course_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `school`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grade_has_course_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
